const games = [
    {
        "id": "welcome-to-the-moon",
        "title": "웰컴 투 더 문",
        "genre": "패밀리",
        "mechanism": "필기",
        "minPlayers": 1,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 2.46,
        "imageClass": "welcome-moon",
        "icon": "🚀",
        "description": "지구인 여러분, 우리는 지금 심각한 상황에 직면해 있습니다. 우리 행성은 종말을 눈앞에 두고 있습니다...! 우리의 생존은 달을 정복하느냐 마느냐에 달려 있습니다. 우리에게 남은 마지막 희망을 여러분에게 맡깁니다."
    },
    {
        "id": "wyrmspan",
        "title": "용스팬",
        "genre": "전략",
        "mechanism": "엔진 빌딩",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "90분",
        "difficulty": 2.81,
        "imageClass": "wyrmspan",
        "icon": "🐉",
        "description": "온갖 크기, 색상, 형태를 띤 드래곤들! 용류학자가 되어 다양한 드래곤의 생태를 연구하세요. 동굴을 굴착하고 자원을 마련해서 드래곤을 유인하세요. 드래곤들 고유의 능력과 상성을 면밀히 고려하세요."
    },
    {
        "id": "terminus",
        "title": "터미너스",
        "genre": "전략",
        "mechanism": "론 델, 영향력",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "120분",
        "difficulty": 3.67,
        "imageClass": "terminus",
        "icon": "🚇",
        "description": "여러분의 교통 회사는 도시의 지구들을 연결하는 지하철 터널과 정거장을 건설하기 위해 고용되었습니다. 과연 여러분의 프로젝트는 순조롭게 진행될까요? 경제가 변화하고 자원이 점점 희소해지는 가운데, 여러분은 서로를 앞지르기 위해 치열한 전략 싸움을 펼치며, 공공 프로젝트 목표와 개인 비밀 의제를 달성해 명성을 얻어야 합니다."
    },
    {
        "id": "life-of-amazonia",
        "title": "라이프 오브 아마조니아",
        "genre": "패밀리",
        "mechanism": "백 빌딩",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "120분",
        "difficulty": 2.83,
        "imageClass": "life-amazonia",
        "icon": "🦜",
        "description": "아마존에 오신 여러분, 환영합니다! 세계에서 가장 다채로운 생태계를 지닌 아마존. 지구상 10%의 생물종이 서식하는 공간 아마존을 더욱 풍요롭게 가꾸기 위해, 세계 최대의 비영리 과학 기구 굿 코멧 협회가 여러분을 아마존 열대 우림으로 초대했습니다. 여러분은 자신만의 아마존 보존 기구를 운영하여 아마존의 정글을 되살려야 합니다!",
        "expansion": "라이프 오브 아마조니아 : 미니 확장"
    },
    {
        "id": "arcs",
        "title": "아크스",
        "genre": "전략",
        "mechanism": "트릭 테이킹, 영향력",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "120분",
        "difficulty": 3.42,
        "imageClass": "arcs",
        "icon": "🌌",
        "description": "혼돈에 휩싸인 은하계의 끝자락, 혹독하고 위험한 리치의 가장자리에 당신의 문명이 존재합니다. 당신은 이 절체절명의 시기에 한 우주 문명의 지도자가 되어 파편화된 은하의 문명을 개척해야 합니다.",
        "expansion": "아크스 : 리더&로어 팩"
    },
    {
        "id": "phoenix-new-horizon",
        "title": "피닉스 뉴 호라이즌",
        "genre": "전략",
        "mechanism": "일꾼 놓기",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "100분",
        "difficulty": 3.22,
        "imageClass": "phoenix",
        "icon": "🔥",
        "description": "우리의 세계는 핵무기로 인해 파괴되었고, 인류는 지난 수십 년간 지하로 피신했습니다. 이제 우리는 기술의 발전에 힘입어, \"피닉스 프로젝트\"의 이름 아래 고향으로 돌아갑니다. 저 땅 위에는 희망으로 가득한 세상이 우리를 기다리고 있습니다!"
    },
    {
        "id": "clank-catacombs",
        "title": "클랭크 카타콤",
        "genre": "패밀리",
        "mechanism": "덱 빌딩",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "80분",
        "difficulty": 2.5,
        "imageClass": "clank-catacombs",
        "icon": "🏰",
        "description": "드래곤의 보물을 들고 튀어라! 단, 잡히지 말 것! 본 드래곤 엄브록 베스나가 거처하는 지하 묘지에는 보물이 가득합니다. 드래곤의 눈을 피해 보물을 챙기고 탈출하세요. 엄청난 부와 명예가 여러분을 기다리고 있습니다. 물론 살아서 돌아올 수 있다면 말이죠... 아무리 큰 부를 얻어도 죽으면 그저 모든 것이 허망한 법!"
    },
    {
        "id": "jisogi",
        "title": "지소기 : 애니메이션 스튜디오 타이쿤",
        "genre": "패밀리",
        "mechanism": "일꾼 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "80분",
        "difficulty": 2.91,
        "imageClass": "jisogi",
        "icon": "🎬",
        "description": "대형 스튜디오 붕괴, 최대 애니메이션 스튜디오 중 한 곳이 파산하면서, 재능 있는 수많은 직원이 실직 위기에 처했습니다. 그 직후, 일부 베테랑 관리자들이 투자자들을 설득해 기발한 해결책을 마련했습니다. 이 중요한 문화 산업을 보호하기 위해 더 작고 전문 분야에 특화된 스튜디오들의 네트워크를 구축하자는 것이었습니다."
    },
    {
        "id": "scout",
        "title": "스카우트",
        "genre": "패밀리",
        "mechanism": "핸드 관리, 클라이밍",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "20분",
        "difficulty": 1.38,
        "imageClass": "scout",
        "icon": "🎪",
        "description": "어느 날 갑자기 서커스 단장이 되어버린 당신! 경쟁 서커스단을 능가할 멋진 쇼를 기획해야 합니다. 더 멋진 쇼를 위해서는 더 강한 조합의 멤버가 필요합니다. 능숙한 솜씨로 새로운 단원을 '스카우트'하고 강력한 조합으로 '쇼'를 펼쳐서 가장 많은 점수를 획득하세요!"
    },
    {
        "id": "azul-sintra",
        "title": "아줄 : 신트라의 스테인드글라스",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, 드래프트",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "40분",
        "difficulty": 2.01,
        "imageClass": "azul-sintra",
        "icon": "🎨",
        "description": "아줄레주로 에보라 왕궁 벽면을 아름답게 장식했던 포르투갈의 왕 마누엘 1세를 기억하시나요? 이제 그는 신트라 왕궁으로 눈을 돌려, 왕궁 유리창을 눈부신 스테인드글라스로 꾸미려 합니다. 여러분은 스테인드글라스 장인이 되어 자신의 유리 세공 실력을 뽐내야 합니다. 보는 이들의 감탄을 자아낼 아름다운 스테인드글라스를 완성할 사람은 누구일까요?"
    },
    {
        "id": "parks-summit",
        "title": "파크스 서밋에디션",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "45분",
        "difficulty": 2.38,
        "imageClass": "parks-summit",
        "icon": "⛰️",
        "description": "동틀 무렵부터 해질녘까지. 봄, 여름, 가을 세 계절간 미국 국립공원의 오솔길을 따라 걸어보세요. 요세미티의 웅장한 하프돔에서 사진을 찍기도 하고, 에버글레이즈 호수 아래에서 악어를 찾을 수도 있죠. 하와이 화산의 열기를 느끼거나, 아치스 산맥 위로 밤하늘에 수놓인 별들을 만날 수도 있어요! 국립공원의 숨막히는 경관을 사진으로 남기고 나만의 앨범을 만들어보세요. 미국의 거대한 대자연 속을 걸어보세요."
    },
    {
        "id": "looping-louie",
        "title": "루핑루이 더블 어택",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "10분",
        "difficulty": 1.0,
        "imageClass": "looping-louie",
        "icon": "✈️",
        "description": "이젠 두 대의 비행기가 날아옵니다! 닭을 지키세요!"
    },
    {
        "id": "gungsin",
        "title": "궁신",
        "genre": "파티",
        "mechanism": "핸드 관리",
        "minPlayers": 3,
        "maxPlayers": 5,
        "playTime": "25분",
        "difficulty": 1.35,
        "imageClass": "gungsin",
        "icon": "🎭",
        "description": "오늘 밤, 여왕께서 만찬을 여십니다. 여왕 폐하께서 주최하는 오늘의 만찬은 여러분이 총애하는 가문이 여왕 폐하의 눈에 들 좋은 기회입니다. 여왕 폐하의 눈에 띌 수만 있다면 험담과 협잡, 그 어떤 지저분한 계략도 마다할 수 없습니다.",
        "images": "궁신.png"

    },
    {
        "id": "dale-of-merchants",
        "title": "상인들의 계곡",
        "genre": "패밀리",
        "mechanism": "덱 빌딩",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 2.29,
        "imageClass": "dale-of-merchants",
        "icon": "🐿️",
        "description": "세계 각지에서 모여든 유명한 동물 상인들이 무역 대회에 참가하기 위해 데일로 모였습니다. 이들의 목표는 단 하나, 우승자로서 전설적인 길드의 새로운 일원이 되는 것입니다. 플레이어는 이 상인들이 되어 새로운 기술을 배우고, 물품을 거래하며, 재고를 관리합니다. 누구보다 먼저 화려한 상점 진열대를 완성한 플레이어가 게임의 승자가 되며, 길드에 입장할 수 있는 자격을 얻게 됩니다!",
        "expansion": "상인들의 계곡 2, 3, 컬렉션"
    },
    {
        "id": "middle-ages",
        "title": "미들 에이지",
        "genre": "패밀리",
        "mechanism": "타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "30분",
        "difficulty": 2.04,
        "imageClass": "middle-ages",
        "icon": "🏰",
        "description": "당신은 한 영지의 영주이며, 그 미래는 당신의 손에 달려 있습니다. 농지와 방앗간을 세워 농업을 발전시킬 것인가? 아니면 경건한 교회를 건설하는 길을 택할 것인가? 혹은 호화로운 궁전에서 잔치를 즐기는 삶을 선호할지도 모릅니다. 당신의 방식대로 땅을 개발하고, 왕국에서 가장 영향력 있는 영주가 되십시오."
    },
    {
        "id": "art-society",
        "title": "아트 소사이어티",
        "genre": "패밀리",
        "mechanism": "경매",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 1.86,
        "imageClass": "art-society",
        "icon": "🖼️",
        "description": "미술품 감정가로서 가장 유행하는 컬렉션을 만들어 동료들에게 깊은 인상을 남기세요! 가장 인기 있는 예술 작품을 입찰하고, 응접실 벽면에 전시하여 현지 예술계가 부러워할 만한 세련된 갤러리를 꾸며 보세요. 하지만 조심하세요! 유행은 한순간이고 트렌드는 예측하기 어렵습니다. 여러분과 동료 수집가들이 구매하지 않은 그림은 결국 미술관에 전시되어 다른 컬렉션의 가치를 바꿀 수도 있습니다."
    },
    {
        "id": "limit",
        "title": "리미트",
        "genre": "전략",
        "mechanism": "협잡",
        "minPlayers": 1,
        "maxPlayers": 6,
        "playTime": "120분",
        "difficulty": 3.45,
        "imageClass": "limit",
        "icon": "🌍",
        "description": "〈리미트〉는 산업혁명이 시작된 1850년부터 가까운 미래인 2060년까지를 다루는 국가 운영 시뮬레이션 게임으로, 플레이어들은 가상의 국가를 이끄는 지도자가 되어 국가 시스템 안에서 서로 경쟁하게 됩니다. 모든 국가는 동일한 조건으로 게임을 시작하지만, 지도자의 정치적 결정에 따라 각자 다른 형태로 발전해 나갑니다. 플레이어가 결정한 정책은 국민의 생활 수준과 자원 생산 능력, 사회 안정성 등에 영향을 주며, 다른 국가 및 세계 정세에 영향을 미치기도 합니다."
    },
    {
        "id": "chop-chop-dice",
        "title": "찹찹 다이스",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.36,
        "imageClass": "chop-chop-dice",
        "icon": "🥕",
        "description": "주사위로 재료를 모아서 세계 각국의 요리를 완성해보세요!"
    },
    {
        "id": "new-york-new-york",
        "title": "뉴욕 뉴욕",
        "genre": "파티",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.29,
        "imageClass": "new-york",
        "icon": "🗽",
        "description": "크럼스크럼스가 '잠들지 않는 도시' 뉴욕에 찾아왔습니다. 자유의 여신상부터 베슬에 이르기까지 12장의 타일을 번호 순서대로 배치하여 아름답게 그려진 뉴욕의 풍경을 완성하세요."
    },
    {
        "id": "fibonachos",
        "title": "피보나초",
        "genre": "파티",
        "mechanism": "트릭 테이킹",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "20분",
        "difficulty": 1.0,
        "imageClass": "fibonachos",
        "icon": "🌮",
        "description": "나초들이 저마다의 매운맛을 얻기 위해 모여들었습니다. 나초 카드를 내려놓으세요. 가장 높은 숫자의 나초가 승리하지만, '피보나초'가 나온다면 승패의 행방은 묘연해질거에요."
    },
    {
        "id": "jalapeno",
        "title": "할라피뇨",
        "genre": "파티",
        "mechanism": "트릭 테이킹",
        "minPlayers": 3,
        "maxPlayers": 9,
        "playTime": "45분",
        "difficulty": 1.4,
        "imageClass": "jalapeno",
        "icon": "🌶️",
        "description": "잘 차려진 식사를 망치는건 어렵지 않습니다. 내 식탁은 훌륭하게 차리고, 남의 식탁에는 할라피뇨를 끼워넣어 눈물나게 매콤한 식사를 선물해보세요!"
    },
    {
        "id": "beaver-creek",
        "title": "비버 크릭",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "30분",
        "difficulty": 1.0,
        "imageClass": "beaver-creek",
        "icon": "🦫",
        "images": "비버크릭.jpg",
        "description": "여러분은 댐 짓기 전문가 비버가 되어서 댐이 무너지지 않게 친구들과 경쟁해야 합니다. 과연 여러분은 가장 똑똑한 비버가 될 수 있을까요?"
    },
    {
        "id": "stubborn-mules",
        "title": "고집센 당나귀",
        "genre": "파티",
        "mechanism": "주사위",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "20분",
        "difficulty": 1.0,
        "imageClass": "stubborn-mules",
        "icon": "🫏",
        "images": "고집센당나귀.png",
        "description": "우리는 주인의 말을 듣지 않는 당나귀들입니다. 당나귀와 주인들은 주사위 3개를 굴려 이동하는데, 결과적으로 주인들에게서 최대한 멀리 떨어진 당나귀가 승리하게 됩니다. 주인들이 가장 늦게 들어온다면 1등을 했던 당나귀가 승리하고, 주인들이 먼저 들어온다면 가장 늦게 들어오는 당나귀가 승리합니다."
    },
    {
        "id": "mr-smith",
        "title": "스위스 사는 스미스씨",
        "genre": "파티",
        "mechanism": "스토리",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "15분",
        "difficulty": 1.0,
        "imageClass": "mr-smith",
        "icon": "🇨🇭",
        "description": "잰말놀이, Tongue-Twister는 발음하기 어려운 문장을 빨리 읽거나 반복해서 읽는 놀이입니다. 펼쳐진 단어 카드들을 실수 없이 빠르게 읽어내어 승리를 쟁취하세요."
    },
    {
        "id": "cash-a-catch",
        "title": "캐시 어 캐치",
        "genre": "파티",
        "mechanism": "순발력, 셋 컬렉션",
        "minPlayers": 3,
        "maxPlayers": 5,
        "playTime": "25분",
        "difficulty": 1.56,
        "imageClass": "cash-a-catch",
        "icon": "🐟",
        "description": "북적지근한 수산 시장의 경매에 참여하세요! 가격은 정해져 있고, 이번 판에 신선한 해산물이 얼마나 많이 나오느냐가 관건이겠습니다. 따온 해산물들은 상하지 않게 보관하세요. 적절한 때에 팔아 많은 돈을 벌어야 하거든요."
    },
    {
        "id": "dream-home",
        "title": "드림 홈",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.66,
        "imageClass": "dream-home",
        "icon": "🏠",
        "description": "여러분이 꿈꾸던 드림 홈을 만들어 보세요! 1층에는 벽난로가 설치된 넓은 거실이 있고 2층에는 어린이 놀이방과 서재가 있습니다. 누구나 한번 쯤은 상상해보았을 법한 정원 달린 2층짜리 단독 주택. 부엌과 욕실은 당연히 있어야겠고, 지붕은 보라색이 좋을까 빨간색이 좋을까? 상상만으로 즐거운 나의 집 설계를 테이블 위에서 구현해보세요."
    },
    {
        "id": "isle-of-skye",
        "title": "스카이섬 : 빅 박스",
        "genre": "패밀리",
        "mechanism": "타일 놓기, 셋 컬렉션, 경매",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "60분",
        "difficulty": 2.2,
        "imageClass": "isle-of-skye",
        "icon": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "description": "족장에서 왕이 되기까지."
    },
    {
        "id": "meadow",
        "title": "메도우",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "70분",
        "difficulty": 2.25,
        "imageClass": "meadow",
        "icon": "🦊",
        "description": "가장 위대한 관찰자가 되기 위한 여정을 떠나보세요! 여러분은 지도 한 장을 들고, 경이로운 이야기로 가득 찬 자연 속으로 떠납니다. 다양한 지식을 바탕으로 경이로운 풍경과 동식물들을 발견하고, 모닥불에 둘러 앉아 여러분이 관찰한 것들을 다른 사람과 나누며 경쟁해 보세요!",
        "expansion": "메도우 : 하류, 메도우 : R 봉투"
    },
    {
        "id": "perch",
        "title": "퍼치",
        "genre": "패밀리",
        "mechanism": "영향력, 핸드 관리",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "40분",
        "difficulty": 2.38,
        "imageClass": "perch",
        "icon": "🦅",
        "description": "Perch(횃대)에서 벌어지는 새들의 전투! 플레이어는 장소들을 장악하기 위해 자신 무리의 새들을 지휘하며 겨루게 됩니다. 특정 장소에 가장 많은 새를 배치하고, 적을 횃대에서 쫓아내고, 수적 우위를 차지하며 승점을 획득하고 피조물들을 조종하세요."
    },
    {
        "id": "avenue",
        "title": "애비뉴",
        "genre": "파티",
        "mechanism": "롤 앤 라이트",
        "minPlayers": 1,
        "maxPlayers": 10,
        "playTime": "15분",
        "difficulty": 1.39,
        "imageClass": "avenue",
        "icon": "🍇",
        "description": "포도농장에 길을 잇자! 맛있는 포도를 성과 농장에 연결시켜 보세요. 가장 많은 점수를 얻은 사람이 승리할 수 있답니다!"
    },
    {
        "id": "next-station-paris",
        "title": "넥스트 스테이션 : 파리",
        "genre": "패밀리",
        "mechanism": "롤 앤 라이트",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "25분",
        "difficulty": 1.68,
        "imageClass": "next-station-paris",
        "icon": "🗼",
        "description": "파리가 지금껏 보지 못했던 최고의 지하철 기획자가 되세요!"
    },
    {
        "id": "sea-salt-paper",
        "title": "종이와 바다",
        "genre": "파티",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.48,
        "imageClass": "sea-salt-paper",
        "icon": "🌊",
        "description": "손에 카드를 모으고, 효과를 발휘하고, 라운드를 끝낼 주도권을 가져오세요. 점수를 더 얻기 위해 상대방에게 한 턴을 줄만큼, 당신은 과감하십니까?",
        "expansion": "종이와 바다 : 확장팩"
    },
    {
        "id": "fertility",
        "title": "퍼틸리티",
        "genre": "패밀리",
        "mechanism": "타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "35분",
        "difficulty": 1.96,
        "imageClass": "fertility",
        "icon": "🏜️",
        "description": "플레이어들은 파라오의 명을 받은 고대 이집트의 주지사로서 나일 유역의 대도시와 그 주변 지역을 다스린다. 범람이 끝나고 비옥해진 나일 계곡의 토지에서 자원을 수집하고, 수익성이 좋은 상점을 건설해 상품을 공급하며 도시를 키워나가고 오벨리스크와 피라미드, 스핑크스, 사원 등 각자의 상징 기념물을 건설하며, 이를 통해 파라오의 영광을 드높이고 부를 축적해라."
    },
    {
        "id": "gang-of-dice",
        "title": "갱 오브 다이스",
        "genre": "파티",
        "mechanism": "주사위",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.5,
        "imageClass": "gang-of-dice",
        "icon": "🎲",
        "description": "조직의 패권을 차지하기 위한 주사위 경쟁. 여러분은 거대 마피아 조직의 간부들입니다. 서로 상대의 부하들을 포섭하여 조직의 패권을 장악하기 위해 생쟁을 벌입니다. 모두에게 당신이 이 조직의 진정한 실력자라는 것을 보여주세요."
    },
    {
        "id": "gouda-gouda",
        "title": "고다고다 켓 어택",
        "genre": "패밀리",
        "mechanism": "주사위, 그리드 이동",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.18,
        "imageClass": "gouda-gouda",
        "icon": "🧀",
        "description": "생쥐 다섯 마리가 한 팀이 되어 먹음직스러운 치즈를 향해 경주합니다."
    },
    {
        "id": "black-fleet",
        "title": "검은 함대",
        "genre": "패밀리",
        "mechanism": "핸드 관리, 지역 이동",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 1.95,
        "imageClass": "black-fleet",
        "icon": "🏴‍☠️",
        "description": "주지사 딸의 몸값을 지불하기 위해, 상선, 해적선, 그리고 해군 선박까지 운용하며 금화를 모으자"
    },
    {
        "id": "giant-octopus",
        "title": "거대문어대소동",
        "genre": "파티",
        "mechanism": "알까기",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "20분",
        "difficulty": 1.37,
        "imageClass": "giant-octopus",
        "icon": "🐙",
        "images": "거대문어대소동.jpg",
        "description": "바닷속 알까기. 문어를 피해 보물을 모아라!"
    },
    {
        "id": "glux",
        "title": "글룩스",
        "genre": "유로",
        "mechanism": "그리드 이동",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 1.62,
        "imageClass": "glux",
        "icon": "💡",
        "description": "글룩스는 빛으로 방을 밝히는 게임입니다. 플레이어는 규칙에 맞게 자신의 불빛 칩을 사용하여 수 싸움에서 승리하고, 게임판의 여러 지역을 자신의 빛으로 밝게 채워야 합니다."
    },
    {
        "id": "isle-of-trains",
        "title": "기차섬",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, AP시스템",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 2.02,
        "imageClass": "isle-of-trains",
        "icon": "🚂",
        "images": "기차섬.png",
        "description": "기차섬에는 최고의 차장들이 모여 있습니다. 역사상 가장 위대한 차장으로 기억되고 싶다고요? 그럼 당장 일을 시작하세요! 계약을 이행하고, 화물과 승객을 운송하며 환상적인 기관차를 만들어 보세요."
    },
    {
        "id": "explorers-of-navoria",
        "title": "나보리아의 탐험가",
        "genre": "패밀리",
        "mechanism": "액션 드래프트, 일꾼 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "60분",
        "difficulty": 2.25,
        "imageClass": "explorers-of-navoria",
        "icon": "🧭",
        "images": "나보리아.jpg",
        "description": "풍부한 판타지 세계를 배경으로 한 몰입형 빌딩 및 일꾼 놓기 게임. 바다에서 떠오른 새로운 대륙을 탐험하는 데 도움이 되는 캐릭터와 상품을 모아보세요. 마을 주민들과 함께 마을에서 상품을 수집하고 큰 보상을 받으세요. 나보리아의 탐험가가 될 준비가 되셨나요?",
        "expansion": "나보리아의 탐험가 : 잊혀진 땅"
    },
    {
        "id": "nyan-nyan-butler",
        "title": "냥냥집사",
        "genre": "파티",
        "mechanism": "셋 컬렉션, 주사위",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "20분",
        "difficulty": 1.0,
        "imageClass": "nyan-nyan-butler",
        "icon": "🐱",
        "description": "사랑스러운 고양이가 되어 집사에게 많은 걸 받아내세요! 가장 풍족한 고양이가 승리합니다!"
    },
    {
        "id": "deep-blue",
        "title": "딥 블루",
        "genre": "패밀리",
        "mechanism": "덱 빌딩",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "45분",
        "difficulty": 1.89,
        "imageClass": "deep-blue",
        "icon": "🌊",
        "description": "이 전설 속의 지도를 산 것은 천재적인 발상이었습니다. 가장 오래되고, 가장 위대하며, 가장 비싼 보물을 실은 난파선이 물 밑에서 당신을 기다리고 있습니다. 잠수복과 산소 탱크를 탑재한 당신의 배는 닻을 내릴 준비를 마쳤습니다. 낭비할 시간이 없습니다! 역사상 가장 큰 보물찾기가 시작되었다는 것입니다!"
    },
    {
        "id": "llama-land",
        "title": "라마랜드",
        "genre": "패밀리",
        "mechanism": "퍼즐",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 2.03,
        "imageClass": "llama-land",
        "icon": "🦙",
        "description": "이곳 고원지대의 자연풍경은 숨 막히게 아름답고... 라마로 가득하네요?! 여러분은 감자와 옥수수, 카카오를 재배하는 농부입니다. 땅 타일을 알맞게 배치하고 계단식 논을 만들고 작물을 모아서 귀여운 라마를 가져와 배치하세요! 때로는 마을 사람들의 도움을 적절히 받는 것도 좋습니다. 과연 누가 가장 성공한 농부가 될까요?"
    },
    {
        "id": "rallyman-gt",
        "title": "랠리맨 GT",
        "genre": "전략",
        "mechanism": "그리드 이동, 주사위",
        "minPlayers": 1,
        "maxPlayers": 6,
        "playTime": "60분",
        "difficulty": 2.22,
        "imageClass": "rallyman-gt",
        "icon": "🏎️",
        "description": "보드판 위에 실제 레이싱 느낌을 담아냈다!",
        "expansion": "랠리맨GT : 챔피언십, 월드투어, GT5 팩, GT4 팩, 팀 챌린지, 아드레날린 팩, KS주사위 팩"
    },
    {
        "id": "run-mule-run",
        "title": "런뮬런",
        "genre": "파티",
        "mechanism": "레이스",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "15분",
        "difficulty": 1.0,
        "imageClass": "run-mule-run",
        "icon": "🐴",
        "description": "\"달려라, 노새!\"는 트로피를 얻기 위한 4마리 노새의 치열한 경주입니다. 색상 화살표를 현명하게 읽어내서 어떤 노새가 우승을 할 지 예측해 보세요."
    },
    {
        "id": "dominion",
        "title": "도미니언",
        "genre": "유로",
        "mechanism": "덱빌딩",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 2.35,
        "imageClass": "dominion",
        "icon": "🏰",
        "description": "내 왕국을 부강하게!"
    },
    {
        "id": "tokyo-highway",
        "title": "도쿄하이웨이 무지개 도시 에디션",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.43,
        "imageClass": "tokyo-highway",
        "icon": "🌈",
        "description": "도쿄 하이웨이의 새로운 에디션 \"무지개 도시\"를 소개합니다! 무지개 도시는 다양한 색상의 새로운 도시 건물과 랜드마크, 그리고 새로운 미션이 포함되어 있습니다. 새로운 전략 점수 옵션과 독특한 도시경관을 만들어보세요!"
    },
    {
        "id": "dragon-castle",
        "title": "드래곤 캐슬",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.98,
        "imageClass": "dragon-castle",
        "icon": "🏯",
        "description": "타일들을 가져와 자신의 성전을 만들자."
    },
    {
        "id": "decrypto",
        "title": "디크립토",
        "genre": "파티",
        "mechanism": "추리",
        "minPlayers": 3,
        "maxPlayers": 8,
        "playTime": "35분",
        "difficulty": 1.81,
        "imageClass": "decrypto",
        "icon": "📟",
    },
    {
        "id": "red7",
        "title": "레드7",
        "genre": "패밀리",
        "mechanism": "클라이밍",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "15분",
        "difficulty": 1.7,
        "imageClass": "red7",
        "icon": "🎨",
        "description": "우승 규칙은 간단하다. 최고의 카드나 한 세트를 가져라. 하지만 너의 차례가 올때도 여전히 같은 게임을 할지는 모른다. 현재 게임을 이기지 못하고 차례가 끝난다면 넌 탈락이다. 최후에 서 있는 사람이 이 라운드에서 승리한다."
    },
    {
        "id": "railroad-ink",
        "title": "레일로드 잉크",
        "genre": "패밀리",
        "mechanism": "롤 앤 라이트",
        "minPlayers": 1,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.45,
        "imageClass": "railroad-ink",
        "icon": "🛤️",
        "description": "주사위를 굴리고 나온 눈금의 노선을 자신의 게임보드에 그립니다. 규칙에 맞게 길을 잘 그려 가장 높은 점수를 얻는 플레이어가 승리합니다."
    },
    {
        "id": "rummikub-select",
        "title": "루미큐브 셀렉트",
        "genre": "패밀리",
        "mechanism": "핸드 관리",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.0,
        "imageClass": "rummikub-select",
        "icon": "🔢",
        "description": "대중적으로 잘 알려진 루미큐브의 대회용 버전. 큼직한 숫자패는 손맛이 좋다. 자신의 숫자를 조합해서 먼저 털어버리면 승리."
    },
    {
        "id": "renature",
        "title": "리네이처",
        "genre": "패밀리",
        "mechanism": "타일 놓기, 영향력",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "50분",
        "difficulty": 2.14,
        "imageClass": "renature",
        "icon": "🌳",
    },
    {
        "id": "maskmen",
        "title": "마스크맨",
        "genre": "패밀리",
        "mechanism": "핸드관리, 클라이밍",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "20분",
        "difficulty": 1.57,
        "imageClass": "maskmen",
        "icon": "🎭",
        "description": "프로레스링 매니저가 되어 이 신인 선수들을 데뷔시키어 우승해야 합니다. 과연 어떤 순서로 시합을 구성하면 좋을까요? #오잉크"
    },
    {
        "id": "manhattan-2022",
        "title": "맨해튼 2022",
        "genre": "패밀리",
        "mechanism": "영향력",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 1.92,
        "imageClass": "manhattan",
        "icon": "🏙️",
        "description": "서로 물고 무는 치열한 쟁탈전 마천루의 주인은 누구인가?",
        "expansion": "맨해튼 : 몬스터"
    },
    {
        "id": "men-at-work",
        "title": "멘 엣 워크",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "45분",
        "difficulty": 1.07,
        "imageClass": "men-at-work",
        "icon": "🏗️",
        "description": "일꾼들은 겁도 없이 보호 장비라고는 안전모뿐인 채 일하고 있습니다. 건축은 안전 장비 없이 높고 높게 올라갑니다. 머지않아 강철 대들보는 현기증 날 정도의 높이에 도달했고 붕괴되기 직전입니다."
    },
    {
        "id": "mojo",
        "title": "모죠",
        "genre": "파티",
        "mechanism": "핸드 관리",
        "minPlayers": 3,
        "maxPlayers": 8,
        "playTime": "30분",
        "difficulty": 1.14,
        "imageClass": "mojo",
        "icon": "🃏",
        "description": "모죠가 모죠? 모죠는 8명까지 함께 즐길 수 있는, 짜릿하고 유쾌한 카드 게임입니다!"
    },
    {
        "id": "libertalia",
        "title": "리버탈리아",
        "genre": "유로",
        "mechanism": "핸드 관리",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "50분",
        "difficulty": 2.24,
        "imageClass": "libertalia",
        "icon": "🏴‍☠️",
        "description": "게일크레스트의 세계에서, 하늘 해적 선단은 바람을 타고 모험, 보물, 영광을 찾아 항해합니다. 이런 선단의 제독으로서, 여러분은 다양하게 구성된 승무원들을 이끌고 보물을 쟁여야 합니다. 그런데, 다른 세력들도 정확히 같은 승무원 패거리를 데리고 왔습니다. 과연 가장 교활한 수를 둬서 부를 거머쥘 해적은 누구일까요? 리버탈리아(Libertalia)란? 해적 선장 James Misson이 세웠다고 하는, 전설 속의 해적 유토피아를 가리킵니다."
    },
    {
        "id": "little-town",
        "title": "리틀 타운",
        "genre": "패밀리",
        "mechanism": "일꾼 놓기, 타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 1.95,
        "imageClass": "little-town",
        "icon": "🏡",
        "description": "귀염뽀짝 신개념 마을 건설 게임. 따사롭고 풍요로운 대지에 새 보금자리를 만들어 볼까요? 보금자리를 찾던 사람들 앞에 광활한 대지가 모습을 드러냈어요. 사람들은 이곳에 <리틀타운>이란 새 도시를 세우기로 했죠! 숲과 호수, 돌산에서 자원을 캐서 건물을 지어봐요. 아참, 든든하게 일하려면 끼니마다 밥도 잘 챙겨 먹어야 해요."
    },
    {
        "id": "reef",
        "title": "리프",
        "genre": "패밀리",
        "mechanism": "핸드 관리, 퍼즐",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.82,
        "imageClass": "reef",
        "icon": "🐠",
        "description": "미션카드를 사용하고 산호초를 개인 보드에 놓으세요. 미션 카드와 개인 보드에 놓인 산호초의 패턴에 따라 점수를 얻습니다. 게임 종료 후 점수가 가장 높은 플레이어가 승리합니다."
    },
    {
        "id": "marrakech",
        "title": "마라케시",
        "genre": "패밀리",
        "mechanism": "그리드 이동, 주사위",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.37,
        "imageClass": "marrakech",
        "icon": "🕌",
        "description": "네가 밟고 있는 것은 누구의 양탄자? 2009년 멘사 셀렉트에 선정 된 마라케시! 마라케시 양탄자 시장을 배경으로 알록달록 양탄자를 누구보다 많이 진열하고 많이 팔아야 승리를 하는 아기자기하고 재미있는 보드게임!"
    },
    {
        "id": "burger-burger",
        "title": "버거가 버거워",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "15분",
        "difficulty": 1.0,
        "imageClass": "burger-burger",
        "icon": "🍔",
        "description": "버거가 서있기 버거울 때까지 재료를 쌓는 신개념 균형 게임!"
    },
    {
        "id": "bunny-kingdom",
        "title": "버니 킹덤",
        "genre": "패밀리",
        "mechanism": "카드 드래프트, 영향력",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "60분",
        "difficulty": 2.26,
        "imageClass": "bunny-kingdom",
        "icon": "🐰",
        "description": "버니킹덤의 모든 영주들은 들어라! 우리는 드디어 왕국을 확장할 ‘새로운 세계’를 발견하였다. 비옥한 대지와 푸른바다, 다양한 자원이 넘치는 이 새로운 세계를 우리 왕국의 새로운 영토로 삼을 것이다. 버니킹덤의 모든 영주들이여! 새로운 세계를 탐험하고 개척하는 이 영광스러운 대업을 너희에게 맡기고자 한다. 가장 큰 업적을 세운 영주에게 내 친히 ‘토끼중의 토끼’ 칭호와 함께 작위 상승의 상을 내릴 것이다. -버니킹덤 버니왕 3세-"
    },
    {
        "id": "lets-make-a-bus-route",
        "title": "버스 노선을 만들자",
        "genre": "패밀리",
        "mechanism": "롤 앤 라이트",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "30분",
        "difficulty": 1.67,
        "imageClass": "bus-route",
        "icon": "🚌",
        "description": "여러분은 버스 노선을 계획하는 책임자 입니다. 여러 고객층의 요구를 들어줄 수 있는 노선을 만들어 보세요!"
    },
    {
        "id": "venture-angels",
        "title": "벤처엔젤스",
        "genre": "파티",
        "mechanism": "블러핑",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "20분",
        "difficulty": 1.0,
        "imageClass": "venture-angels",
        "icon": "💡",
        "description": "벤처엔젤스에서 당신은 재미로 벤처 기업에 투자하는 억만장자입니다. 각 라운드에서 매력적이지만 위험한 벤처가 등장합니다. 비관적이거나 거품이 낀 벤처와 좋은 벤처를 분류하고 비밀리에 투자하십시오. 각 라운드가 끝날 때마다 비밀 입찰을 공개하고 어떤 벤처가 충분한 투자를 받았는지 확인하십시오. 가장 눈에 띄는 투자를 한 투자자는 성공에 기여한 것에 대해 보상을 받게 됩니다. 게임이 끝날 때 가장 큰 명성을 얻은 투자자가 벤처 엔젤이 됩니다."
    },
    {
        "id": "moon-leap",
        "title": "문립",
        "genre": "파티",
        "mechanism": "주사위, 레이스",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.1,
        "imageClass": "moon-leap",
        "icon": "🌙",
        "description": "달 위의 우주인들이 가장 높은 점수 칸에 도달하기 위해서 점프의 레이싱을 펼칩니다. 게임이 끝났을 때 각자 도달한 칸의 숫자와 말의 숫자를 곱하여 가장 높은 점수를 얻은 플레이어가 승리합니다. 잊지 마세요! 남에서 섬프로 이동하는 것이 쉽지만은 않습니다."
    },
    {
        "id": "mino-dice",
        "title": "미노 다이스",
        "genre": "파티",
        "mechanism": "주사위",
        "minPlayers": 3,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.57,
        "imageClass": "mino-dice",
        "icon": "🎲",
        "description": "황소의 머리를 가진 거인 Minotaur. 그는 미궁 안에서 먹잇감이 나타나면 주사위를 굴리는 취미를 갖고 있습니다. 하지만 그는 승부를 운에만 맡기지 않습니다. 손에 들어온 주사위를 보고 몇 번을 이길 수 있을지, 또는 이길 수 없을지에 승부를 거세요. 예측만 맞는다면 어쩌면 Minotaur 도 쓰러뜨릴 수 있습니다."
    },
    {
        "id": "planet-unknown",
        "title": "미지의 행성",
        "genre": "유로",
        "mechanism": "엔진 빌딩, 퍼즐",
        "minPlayers": 1,
        "maxPlayers": 6,
        "playTime": "70분",
        "difficulty": 2.23,
        "imageClass": "planet-unknown",
        "icon": "🌍",
        "images": "미지의 행성.JPG",
        "description": "지구는 고갈되고 있습니다. 바야흐로, 인류의 미래를 위한 행성 개척 프로젝트가 시작됩니다."
    },
    {
        "id": "valletta",
        "title": "발레타",
        "genre": "패밀리",
        "mechanism": "핸드 관리, 일꾼 놓기, 엔진 빌딩",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "60분",
        "difficulty": 2.32,
        "imageClass": "valletta",
        "icon": "⛪",
    },
    {
        "id": "circus-flohcati",
        "title": "벼룩 서커스",
        "genre": "파티",
        "mechanism": "셋 컬렉션",
        "minPlayers": 3,
        "maxPlayers": 5,
        "playTime": "15분",
        "difficulty": 1.22,
        "imageClass": "circus-flohcati",
        "icon": "🎪",
        "description": "높은 점수의 서커스 카드를 모으세요."
    },
    {
        "id": "stars-wish",
        "title": "별의 소원",
        "genre": "패밀리",
        "mechanism": "트릭 테이킹, 협력",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "25분",
        "difficulty": 2.25,
        "imageClass": "stars-wish",
        "icon": "🌟",
        "description": "별의 소원을 이뤄주세요. 더 빛나는 존재가 되기 위해, 별은 사람의 감정을 이해하고 싶어 합니다. 감정을 모으면 소원을 이룰 수 있지만, 무리한 행동은 오히려 빛을 잃게 하니, 균형점을 찾아야 합니다."
    },
    {
        "id": "break-the-cube",
        "title": "브레이크 더 큐브",
        "genre": "패밀리",
        "mechanism": "추리",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "25분",
        "difficulty": 1.57,
        "imageClass": "break-the-cube",
        "icon": "🧊",
        "description": "“브레이크 더 큐브”에서 당신은 상대방 스크린 뒤에 숨겨진 블럭 배치를 가장 먼저 맞혀야 합니다. 상대방의 블럭 배치에 관한 질문을 하고, 정보를 얻으세요. 상대방보다 먼저 알아내면 승리합니다!"
    },
    {
        "id": "blueprints",
        "title": "블루 프린트",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, 주사위",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.69,
        "imageClass": "blueprints",
        "icon": "🏗️",
        "description": "플레이어는 건축가가 되어 주어진 재료로 건물을 만듭니다. 다양한 배치로 점수를 얻어보세요."
    },
    {
        "id": "billabong",
        "title": "빌라봉",
        "genre": "파티",
        "mechanism": "레이스",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "15분",
        "difficulty": 1.88,
        "imageClass": "billabong",
        "icon": "🦘",
        "description": "20마리의 캥거루들이 '빌라봉' 호수의 주위를 돌아 위대한 경주를 펼칩니다. 캥거루는 서로를 뛰어넘으며 달리는데, 여건만 된다면 몇 마리의 캥거루라도 뛰어넘을 수 있습니다. 자신의 캥거루를 모두, 먼저 결승선을 통과시키는 플레이어가 승리합니다. 공정한 경주를 위해 심판 캥거루가 항시 대기 중입니다."
    },
    {
        "id": "sagrada",
        "title": "사그라다",
        "genre": "패밀리",
        "mechanism": "주사위 드래프트",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "45분",
        "difficulty": 1.92,
        "imageClass": "sagrada",
        "icon": "⛪",
        "description": "화려한 스테인드글라스를 창조해보세요!",
        "expansion": "사그라다 : 5,6인 확장"
    },
    {
        "id": "shallow-sea",
        "title": "샐로우 씨",
        "genre": "패밀리",
        "mechanism": "퍼즐",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 2.0,
        "imageClass": "shallow-sea",
        "icon": "🌊",
        "description": "다양한 물고기, 해양 생물, 산호를 전략적으로 배치해 자신만의 아름다운 바닷속 풍경을 만들어보세요!",
        "expansion": "샐로우 씨 : 희귀 물고기, 샐로우 씨 : 산란 시즌"
    },
    {
        "id": "survive",
        "title": "서바이브",
        "genre": "파티",
        "mechanism": "주사위, AP시스템",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.37,
        "imageClass": "survive",
        "icon": "🏝️",
        "description": "섬이 가라앉는다. 배를 타고 바다의 생물들을 피해 살아남자.",
    },
    {
        "id": "sunset-over-water",
        "title": "선셋 오버 워터",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "20분",
        "difficulty": 1.68,
        "imageClass": "sunset-over-water",
        "icon": "🌅",
        "description": "아름다운 자연을 그림으로 남겨보세요!"
    },
    {
        "id": "7-wonders-architects",
        "title": "7원더스 건축가들",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 7,
        "playTime": "25분",
        "difficulty": 2.0,
        "imageClass": "7-wonders-architects",
        "icon": "🏛️",
        "description": "각 문명을 상징하는 장대한 불가사의를 건축하는 일이 여러분에게 떨어졌습니다. 다른 도시들보다 빠르게 위대한 불가사의를 건축 하고 여러분의 문명을 과시해야 합니다."
    },
    {
        "id": "century-golem",
        "title": "센추리 : 골렘 에디션",
        "genre": "패밀리",
        "mechanism": "핸드 관리, 덱 빌딩, 셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "45분",
        "difficulty": 1.77,
        "imageClass": "century-golem",
        "icon": "💎",
        "description": "크리스탈을 이용해서 골렘을 만들어내자."
    },
    {
        "id": "arboretum",
        "title": "수목원",
        "genre": "전략",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 2.16,
        "imageClass": "arboretum",
        "icon": "🌳",
        "description": "나무를 심어 아름다운 산책로를 완성하세요!"
    },
    {
        "id": "super-mega-lucky-box",
        "title": "슈퍼메가 럭키박스",
        "genre": "파티",
        "mechanism": "롤 앤 라이트",
        "minPlayers": 1,
        "maxPlayers": 6,
        "playTime": "20분",
        "difficulty": 1.24,
        "imageClass": "super-mega-lucky-box",
        "icon": "🎁",
        "description": "빙고 게임으로 슈퍼! 메가! 럭키!한 재미를 담아낸 보드게임"
    },
    {
        "id": "swish",
        "title": "스위시",
        "genre": "파티",
        "mechanism": "순발력",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "20분",
        "difficulty": 1.0,
        "imageClass": "swish",
        "icon": "⭕",
        "description": "스위시는 실시간으로 진행되는 재미있는 공간적 사고 게임입니다. 머릿속으로 카드를 조합해 다른 사람보다 먼저 '스위시'를 찾아보세요!"
    },
    {
        "id": "scarabia",
        "title": "스카라비아",
        "genre": "패밀리",
        "mechanism": "타일 놓기",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "10분",
        "difficulty": 1.92,
        "imageClass": "scarabia",
        "icon": "🐞",
        "description": "황금풍뎅이를 발굴해서 점수를 먹자!"
    },
    {
        "id": "hidden-leaders",
        "title": "히든 리더스",
        "genre": "파티",
        "mechanism": "영향력",
        "minPlayers": 3,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.87,
        "imageClass": "hidden-leaders",
        "icon": "👑",
        "description": "황제가 죽고, 오쉬라 섬은 혼란에 빠졌습니다. 자신의 리더가 왕좌를 차지할 수 있도록 본심을 숨긴 채 은밀하게 행동하세요!",
    },
    {
        "id": "startups",
        "title": "스타트 업스",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, 핸드 관리",
        "minPlayers": 3,
        "maxPlayers": 7,
        "playTime": "20분",
        "difficulty": 1.58,
        "imageClass": "startups",
        "icon": "📈",
        "description": "회사의 주식지분을 차지하기 위해 경쟁하는 카드게임. 경쟁에서 승리하여 최대주주가 되세요. #오잉크"
    },
    {
        "id": "splendor-marvel",
        "title": "스플렌더 마블",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.9,
        "imageClass": "splendor-marvel",
        "icon": "💎",
        "description": "슈퍼 히어로 팀의 지휘관이 되어 강력한 팀원들을 모으고, 우주의 절반을 없애려는 타노스의 음모를 막아내세요!"
    },
    {
        "id": "cities",
        "title": "스티즈",
        "genre": "패밀리",
        "mechanism": "일꾼 놓기, 타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.94,
        "imageClass": "cities",
        "icon": "🏙️",
        "description": "도시계획자인 여러분은 시의회의 의뢰를 받아 도시 재개발 계획을 세우고 주택과 사무실, 공원, 여가 공간 등을 어떻게 배치하고 건축할지 결정해야 합니다. 도시마다 요구하는 사항이 다르기에, 이에 맞춰 다양한 요소를 적재적소 배치해야 높은 점수를 얻을 수 있습니다. 과연 누가 세계적으로 유명한 도시를 가장 돋보이게 만드는 설계자가 될까요?"
    },
    {
        "id": "silly-cow",
        "title": "실리 카우",
        "genre": "파티",
        "mechanism": "핸드 관리",
        "minPlayers": 3,
        "maxPlayers": 6,
        "playTime": "25분",
        "difficulty": 1.0,
        "imageClass": "silly-cow",
        "icon": "🐄",
        "description": "동물들이 엉망진창으로 섞여버렸습니다. 동물들을 되찾는 가운데, 말썽쟁이들을 떠넘기려는 게임이 시작되었습니다. 말썽쟁이 소는 옆 사람에게 재빨리 넘기세요."
    },
    {
        "id": "dance-of-ibexes",
        "title": "아이벡스의 춤",
        "genre": "파티",
        "mechanism": "핸드 관리",
        "minPlayers": 2,
        "maxPlayers": 8,
        "playTime": "30분",
        "difficulty": 1.4,
        "imageClass": "dance-of-ibexes",
        "icon": "🐐",
        "description": "소금을 찾아 좋은 자리에 머물고자, 아이벡스 산양들은 오늘도 절벽 위에서 눈치 싸움을 벌입니다. 매 라운드 숫자 타일을 잘 사용하세요. 안전한 자리에 머문다면 참 다행이지만, 독수리의 공격을 받을 수도 있습니다. 누군가 벌점 60점을 받을 때까지, 아이벡스의 눈치 싸움은 계속됩니다."
    },
    {
        "id": "azul",
        "title": "아줄",
        "genre": "유로",
        "mechanism": "셋 컬렉션, 타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.76,
        "imageClass": "azul",
        "icon": "🎨",
        "description": "어떤 타일로 왕국 벽면을 꾸미면 좋을까? 스페인의 알람브라 궁전에 방문한 포르투갈 국왕 마누엘 1세는 궁전 벽면을 장식한 아름다운 타일들에 반해버렸습니다. 포르투갈의 타일 장인이 되어 에보라 왕궁을 화려하게 수놓아 주세요!"
    },
    {
        "id": "deep-sea-adventure",
        "title": "해저 탐험",
        "genre": "파티",
        "mechanism": "주사위",
        "minPlayers": 3,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.18,
        "imageClass": "deep-sea-adventure",
        "icon": "🐙",
        "description": "깊은 바다속으로 보물 사냥을 떠나 보세요~ #오잉크"
    },
    {
        "id": "el-dorado",
        "title": "엘도라도",
        "genre": "패밀리",
        "mechanism": "덱 빌딩",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.92,
        "imageClass": "el-dorado",
        "icon": "🚣",
        "description": "전설적인 황금의 도시를 찾아 울창한 남미 정글을 질주하세요.",
    },
    {
        "id": "thats-pretty-clever",
        "title": "영리한 여우",
        "genre": "전략",
        "mechanism": "롤 앤 라이트",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.9,
        "imageClass": "thats-pretty-clever",
        "icon": "🦊",
        "description": "두뇌의 한계에 도전하는 신감각 주사위 게임! 6가지 색 주사위를 굴리고, 굴린 주사위를 하나씩 골라 점수로 사용합니다. 높은 주사위를 사용하면 높은 점수를 받지만, 대신 그만큼 다음 기회는 줄어들어요. 게임 방법은 간단하지만 점수를 잘 모으려면 머리를 잘 써야한답니다. '롤 앤 라이트' 장르의 붐을 일으킨 명작"
    },
    {
        "id": "twice-as-clever",
        "title": "두 배로 영리한 여우",
        "genre": "패밀리",
        "mechanism": "롤 앤 라이트",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 2.34,
        "imageClass": "twice-as-clever",
        "icon": "🦊🦊",
        "description": "심감각 주사위 게임 <영리한 여우>가 두 배로 영리해져 돌아왔다! 2018년 독일 올해의 게임상 후보"
    },
    {
        "id": "yeti-snack",
        "title": "예티스낵",
        "genre": "파티",
        "mechanism": "퍼즐",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "20분",
        "difficulty": 1.0,
        "imageClass": "yeti-snack",
        "icon": "🍦",
        "description": "이럴수가... 예티의 냉장고가 고장 나버렸어요! 식재료가 모두 녹아버리기 전에, 예티가 원하는 간식을 만들어주세요!"
    },
    {
        "id": "challengers",
        "title": "오토배틀 챌린저스",
        "genre": "패밀리",
        "mechanism": "덱 빌딩",
        "minPlayers": 1,
        "maxPlayers": 8,
        "playTime": "45분",
        "difficulty": 1.79,
        "imageClass": "challengers",
        "icon": "🏁",
        "description": "누가 \"깃발 뺏기\" 토너먼트의 우승컵을 들어올릴까요? 우주 저편의 외계인부터 깊은 바다 괴생물체까지, 각양각색의 실력자들이 오늘 경기장에 모였습니다. 바로 깃발 뺏기 대회에 참여하기 위해서죠! 최강의 팀을 꾸린 자만이 승자가 될 수 있습니다. 운과 실력을 모두 활용해 강력한 팀을 만드세요!"
    },
    {
        "id": "challengers-beach-cup",
        "title": "오토배틀 챌린저스 비치컵",
        "genre": "패밀리",
        "mechanism": "덱 빌딩",
        "minPlayers": 1,
        "maxPlayers": 8,
        "playTime": "45분",
        "difficulty": 2.14,
        "imageClass": "challengers-beach-cup",
        "icon": "🏖️",
        "description": "세계 최고의 인기 스포츠 \"깃발 뺏기\" 토너먼트가 이제 비밀기지의 어두운 골목과 높디높은 산맥 꼭대기까지 그 명성과 열기를 터뜨려 나갑니다! 더 개성 넘치는 선수들로 무장하고, 더 치열해진 깃발 뺏기 토너먼트의 현장 속으로 지금 바로 뛰어드세요!"
    },
    {
        "id": "steal-the-piggy-bank",
        "title": "우리집 돼지저금통을 훔쳤다",
        "genre": "파티",
        "mechanism": "순발력",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "15분",
        "difficulty": 1.2,
        "imageClass": "steal-the-piggy-bank",
        "icon": "🐷",
        "description": "친구들과 즐겁고 긴장감 넘치는 간식 쟁탈전을 벌입니다! 맛있는 간식을 되도록 빨리, 많이 차지하세요!"
    },
    {
        "id": "ubongo-3d",
        "title": "우봉고 3D",
        "genre": "파티",
        "mechanism": "퍼즐",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 2.0,
        "imageClass": "ubongo-3d",
        "icon": "🧱",
        "description": "폴리오미노 게임의 대명사 우봉고가 3D버전으로 나왔습니다. 이제 우봉고 최고 난이도에 도전해 볼까요?"
    },
    {
        "id": "a-wonderful-world",
        "title": "원더풀 월드",
        "genre": "패밀리",
        "mechanism": "카드 드래프트",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "45분",
        "difficulty": 2.32,
        "imageClass": "a-wonderful-world",
        "icon": "🌍",
        "description": "<원더풀 월드>는 디스토피아 테마를 지닌 간단한 전략 게임입니다. 여러분은 각 제국의 지도자가 되어 미래를 설계하고 어떻게 제국을 발전해 나갈지 고민해야 합니다. 지혜로운 판단으로 남들보다 발전된 제국을 만들어 보세요.",
    },
    {
        "id": "enchain",
        "title": "인체인",
        "genre": "파티",
        "mechanism": "순발력",
        "minPlayers": 1,
        "maxPlayers": 6,
        "playTime": "10분",
        "difficulty": 1.0,
        "imageClass": "enchain",
        "icon": "🕵️",
        "description": "카지노에 비밀 요원들이 잠입했습니다. 청소부, 바텐더, 딜러, 노신사 등으로 변장한 요원들은 멋드러지고 특수한 소품들로 비밀스러운 신호를 주고받고 있습니다. 스파이의 암호를 빠르게 해독해 더 많은 요원을 확보하세요."
    },
    {
        "id": "illusion",
        "title": "일루전",
        "genre": "파티",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "15분",
        "difficulty": 1.07,
        "imageClass": "illusion",
        "icon": "👁️",
        "description": "어떤 색깔이 가장 많이 보이나요? 당신의 눈을 믿을 수 있나요? 카드를 색깔 비율대로 놓기만 하면 되는 아주 쉽고 간단한 게임."
    },
    {
        "id": "spots",
        "title": "점박이",
        "genre": "파티",
        "mechanism": "주사위",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.3,
        "imageClass": "spots",
        "icon": "🐶",
        "description": "어떤 강아지에게는 점이 있어요. 주사위에도 점이 있죠. 주사위를 알맞게 배치해서 강아지의 무늬를 완성하고 점수를 얻으세요!"
    },
    {
        "id": "eraser-wrestling",
        "title": "지우개 레슬링",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.0,
        "imageClass": "eraser-wrestling",
        "icon": "🤼",
        "description": "기억 나습니까? 헐크 호건과 동시에, 무한 폭주하던 헐크, 지옥에서 건너 온, 공포의 카리스마 언더 테이커, 나이스한 외모에서 폭발하는 강력한 엘보우, 더락 얼마 전 우리 곁을 떠났지만, 영원한 전사, 워리어, 그들이 다시 새로운 전설을 씁니다."
    },
    {
        "id": "world-wonders",
        "title": "월드원더스",
        "genre": "패밀리",
        "mechanism": "경매, 타일 놓기, 퍼즐",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "60분",
        "difficulty": 2.24,
        "imageClass": "world-wonders",
        "icon": "🏛️",
        "description": "찬란한 도시 문명이 펼쳐집니다. 역사에 길이 남을 고대 도시를 건설하세요.",
        "expansion": "월드원더스 : 문도"
    },
    {
        "id": "world-changers",
        "title": "월드 체인저스",
        "genre": "패밀리",
        "mechanism": "카드 드래프트",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "10분",
        "difficulty": 2.0,
        "imageClass": "world-changers",
        "icon": "📜",
        "description": "새로운 문명을 만들기 위해 과거의 위인들로 팀을 꾸려야 합니다. 각기 장단점이 있는 위인을 당신의 팀으로 데려와 가장 좋은 상승 효과를 만드세요."
    },
    {
        "id": "hey-thats-my-fish",
        "title": "이봐, 이건 내 물고기야!",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "20분",
        "difficulty": 1.45,
        "imageClass": "hey-thats-my-fish",
        "icon": "🐧",
        "description": "빙하가 가라 앉고 있어요! 물고기가 모두 사라지기 전에 건질 수 있는 만큼 잡아보세요. 당신이 하지 않으면, 다른 펭귄들이 잡아갈 거예요. 자기 펭귄 가족의 운명은 각자의 손에 달렸어요. 여러분의 펭귄들은 가장 먹음직스러운 물고기를 잡고 경쟁 상대를 막기 위해 빠르게 줄어드는 빙하를 가로질러 움직여야 합니다. 하지만 경계를 늦춰선 안 됩니다! 빙하 한 조각에 갇힌 펭귄은 더는 물고기를 잡을 수 없으니까요."
    },
    {
        "id": "industria",
        "title": "인더스트리아",
        "genre": "패밀리",
        "mechanism": "경매, 엔진 빌딩",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "120분",
        "difficulty": 2.12,
        "imageClass": "industria",
        "icon": "🏭",
    },
    {
        "id": "chamsaejak",
        "title": "참새작",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "30분",
        "difficulty": 1.75,
        "imageClass": "chamsaejak",
        "icon": "🀄",
        "description": "마작의 초심자 버전"
    },
    {
        "id": "wonder-bowling",
        "title": "원더 볼링",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "15분",
        "difficulty": 1.1,
        "imageClass": "wonder-bowling",
        "icon": " bowling",
        "icon": "🎳",
        "description": "원더 볼링에서는 공을 굴리는 대신 공 막대로 레인을 때려서 진동으로 핀을 쓰러뜨려야 합니다. 단 1개의 핀만 남기면 스트라이크지만 모든 핀을 쓰러뜨리면 페널티를 받게 됩니다. 섬세한 힘 조절로 가장 먼저 목표를 달성하세요!"
    },
    {
        "id": "viking-see-saw",
        "title": "바이킹 시소",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "10분",
        "difficulty": 1.05,
        "imageClass": "viking-see-saw",
        "icon": "⛵",
        "description": "바이킹 시소는 자신의 모든 화물을 배에 가장 먼저 실어야 하는 균형잡기 시소 게임입니다. 모양도 재질도 무게도 각기 다른 다양한 화물을 배의 방향이 바뀌지 않도록 조심스럽게 실어야 합니다. 가장 먼저 화물을 싣는 바이킹은 과연 누가 될까요?"
    },
    {
        "id": "ninja-master",
        "title": "닌자마스터",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "10분",
        "difficulty": 1.0,
        "imageClass": "ninja-master",
        "icon": "🥷",
        "description": "주사위 결과를 빠르고 정확하게 파악해서 가장 높은 점수를 얻을 수 있는 토큰을 가져가세요! 닌자가 은신술을 써서 사라지지는 않았는지 언제 검을 빼앗을지 냉철한 판단은 필수! 과연 누가 닌자 마스터의 자리에 오르게 될까요?"
    },
    {
        "id": "kanagawa",
        "title": "카나가와",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, 일꾼 놓기, 카드 드래프트",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 2.03,
        "imageClass": "kanagawa",
        "icon": "🖌️",
        "description": "붓 끝에서 피어나는 사계의 정취."
    },
    {
        "id": "carcassonne-20th",
        "title": "카르카손 20주년 기념판",
        "genre": "유로",
        "mechanism": "타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "40분",
        "difficulty": 1.89,
        "imageClass": "carcassonne-20th",
        "icon": "🏰",
        "description": "카르카손 20주년 정수가 담긴 기념판! 2001년 독일 올해의 게임상을 수상한 이래로 세계적으로 사랑을 받아온 <카르카손>이 20주년을 기념해 출시했습니다. 20주년 기념판에만 있는 고광택 타일과 특별 규칙으로 게임을 더 화려하게 재밌게 즐겨보세요."
    },
    {
        "id": "cant-stop",
        "title": "캔트 스탑",
        "genre": "파티",
        "mechanism": "주사위",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.14,
        "imageClass": "cant-stop",
        "icon": "🎲",
        "description": "주사위를 굴리고, 2개씩 조합해서 가장 먼저 정상에 오르세요!!! 가장 먼저 3개의 정상에 다다르면 승리합니다."
    },
    {
        "id": "calico",
        "title": "캘리코",
        "genre": "패밀리",
        "mechanism": "타일 배치",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "40분",
        "difficulty": 2.17,
        "imageClass": "calico",
        "icon": "🐱",
    },
    {
        "id": "coffee-rush",
        "title": "커피 러쉬",
        "genre": "패밀리",
        "mechanism": "일꾼 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.8,
        "imageClass": "coffee-rush",
        "icon": "☕",
        "description": "밀려드는 주문을 처리하여 SNS최고 인기 카페에 등극하세요! <커피 러시>는 카페를 경영하며 SNS 평판을 관리하는 게임입니다. 주문을 받아 재료를 준비하고, 음료를 만들어 서빙하세요."
    },
    {
        "id": "cats-run",
        "title": "캣츠런",
        "genre": "파티",
        "mechanism": "주사위, 레이스",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "15분",
        "difficulty": 1.0,
        "imageClass": "cats-run",
        "icon": "🐈",
        "description": "멍구가 풀려났다! 야옹이들아 도망쳐! 여기저기 부딪히며 마당을 돌아다니는 멍구 때문에, 고양이들이 곤경에 처했습니다. 멍구에 부딪히면 저 멀리 날아가니 조심하세요!"
    },
    {
        "id": "codex",
        "title": "코덱스",
        "genre": "패밀리",
        "mechanism": "핸드 관리",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.74,
        "imageClass": "codex",
        "icon": "📔",
        "description": "네 종류의 생물을 기록한 페이지를 이어붙여 신비한 고문서 코덱스를 완성해보세요."
    },
    {
        "id": "code-777",
        "title": "코드 777",
        "genre": "패밀리",
        "mechanism": "추리",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "60분",
        "difficulty": 2.32,
        "imageClass": "code-777",
        "icon": "📟",
        "description": "스파이가 되어 모스코드를 사용해 암호를 주고 받자. #보드피아 책박스"
    },
    {
        "id": "cookierun-loveletter",
        "title": "쿠키런 러브레터",
        "genre": "파티",
        "mechanism": "핸드 관리",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "20분",
        "difficulty": 1.12,
        "imageClass": "cookierun-loveletter",
        "icon": "🍪💌",
        "description": "괴도맛 쿠키는 어디에 있을까? 호두맛 쿠키를 도와 괴도맛 쿠키의 흔적을 찾고, 이를 위해 적절히 다른 쿠키들의 도움을 받으세요. 게임에서 승리하기 위해서는 호두맛 쿠키처럼 번뜩이는 추리력을 발휘해 마지막까지 살아남아야 한답니다!"
    },
    {
        "id": "cookierun-kingdom",
        "title": "쿠키런 킹덤",
        "genre": "패밀리",
        "mechanism": "일꾼 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 2.0,
        "imageClass": "cookierun-kingdom",
        "icon": "🍪🏰",
        "description": "마녀들이 구워낸 달콤하고 바삭한 키들의 세상... 소울잼을 가진 영웅 쿠키들의 등장으로 쿠키 문명은 대부흥을 맞이 하는데... 그러나 그것도 잠시... 어둠을 자처하는 자들의 등장으로 온 땅에 혼돈의 그림자가 드리우기 시작했다. 지금 바로 쿠키들의 운명이 걸린 최후의 전쟁이 시작된다."
    },
    {
        "id": "cubitos",
        "title": "큐비토스",
        "genre": "파티",
        "mechanism": "주사위 빌딩, 레이스",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "60분",
        "difficulty": 2.13,
        "imageClass": "cubitos",
        "icon": "🎲🏎️",
        "description": "경쾌한 주사위 레이스, 손 맛 좋은 주사위 엔진 빌딩게임. 주사위를 잘 조합해 콤보를 터트리면 부스터 온!"
    },
    {
        "id": "crime-hotel",
        "title": "크라임 호텔",
        "genre": "패밀리",
        "mechanism": "추리, 트릭 테이킹",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.6,
        "imageClass": "crime-hotel",
        "icon": "🏨❓",
    },
    {
        "id": "kingdomino-stone-age",
        "title": "킹도미노 : 석기시대",
        "genre": "패밀리",
        "mechanism": "타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "25분",
        "difficulty": 2.14,
        "imageClass": "kingdomino-stone-age",
        "icon": "🍖",
        "description": "눈 떠보니 석기시대 부족장이 되어있다? 우리 부족, 어디까지 성장할 수 있을까? 2017 독일 올해의 게임상 ‘킹도미노’가 석기시대 버전으로 돌아왔습니다."
    },
    {
        "id": "tasso-banana",
        "title": "타쏘 바나나",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "15분",
        "difficulty": 1.0,
        "imageClass": "tasso-banana",
        "icon": "🍌",
        "description": "바나나 나무에 바나나가 열립니다. 바나나 스틱을 보드 위에 쌓으세요. 다른 스틱 두 개 위에 쌓는 데 성공했다면 스틱을 한 번 더 놓을 수 있습니다. 자신의 스틱을 먼저 모두 쌓으면 승리합니다."
    },
    {
        "id": "tasso-safari",
        "title": "타쏘 사파리",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "10분",
        "difficulty": 1.0,
        "imageClass": "tasso-safari",
        "icon": "🦓",
        "description": "스틱과 스틱사이의 거리 가늠 게임"
    },
    {
        "id": "takenoko",
        "title": "타케노코",
        "genre": "패밀리",
        "mechanism": "AP시스템, 타일 놓기, 셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 1.98,
        "imageClass": "takenoko",
        "icon": "🐼",
        "description": "여러분은 친교의 선물로 받은 거대한 판다를 잘 돌봐야 합니다. 땅을 견착하고 물을 대며, 판다가 먹을 대나무를 키워나가세요. 하지만 다 자라지도 않은 새싹도 먹어 치우는 판다의 주체할 수 없는 식욕을 만족시킬 수 있을까요?",
        "expansion": "타케노코 : 치비스"
    },
    {
        "id": "takoyaki-master",
        "title": "타코야끼 마스터",
        "genre": "파티",
        "mechanism": "덱스터리티",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "10분",
        "difficulty": 1.0,
        "imageClass": "takoyaki-master",
        "icon": "🍡",
        "description": "누구보다 먼저 타코야끼를 만드세요!"
    },
    {
        "id": "ra",
        "title": "태양신 라",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, 경매",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "60분",
        "difficulty": 2.35,
        "imageClass": "ra",
        "icon": "🌞",
        "description": "태양신 라라는 태양의 힘을 사용해 다른 플레이어보다 더 자신의 왕조를 발전시키는 것을 목표로 합니다. 다른 플레이어들과 경매를 통해 발전있는 타일들을 효율적으로 얻어 자신의 왕조를 번영시키세요!"
    },
    {
        "id": "tokaido-deluxe",
        "title": "토카이도 디럭스",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "45분",
        "difficulty": 1.97,
        "imageClass": "tokaido-deluxe",
        "icon": "🗾",
        "description": "플레이어는 옛 일본의 여행객입니다. 플레이어들은 권위있는 토카이도를 따라 가능한 풍부한 경험으로 여행을 채우기 위해 노력할 것입니다. 풍부한 경험을 채우기 위해서는, 그들은 아름다운 전원지역을 따라 여행하고 맛있는 특선 요리들을 맛보며, 특산품들을 구입하고, 온천지의 혜택을 즐기며 잊지못할 만나의 추억을 간직해야 합니다.",
        "expansion": "토카이도 : 교차로, 토카이도 : 마츠리"
    },
    {
        "id": "topiary",
        "title": "토피어리",
        "genre": "패밀리",
        "mechanism": "일꾼 놓기, 타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.71,
        "imageClass": "topiary",
        "icon": "✂️🌳",
        "description": "아름다운 정원에서 예술품을 감상합시다. 다만 순서대로"
    },
    {
        "id": "tonga-bonga",
        "title": "통가봉가",
        "genre": "패밀리",
        "mechanism": "영향력",
        "minPlayers": 3,
        "maxPlayers": 4,
        "playTime": "45분",
        "difficulty": 1.68,
        "imageClass": "tonga-bonga",
        "icon": "⛵",
        "description": "통가봉가에서 여러분은 돈을 벌기 위해 자신의 배를 운용하는 야심찬 배의 주인입니다. 유능한 선원을 고용해서 남보다 빨리 도착할수록 더 큰 돈을 벌게 됩니다. 최고의 선원을 균형있는 투자로 고용하고 최고의 배의 주인이 되어보세요!"
    },
    {
        "id": "triqueta",
        "title": "트리게타",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "30분",
        "difficulty": 1.21,
        "imageClass": "triqueta",
        "icon": "💠",
        "description": "정확한 3개의 토큰으로 완벽한 트리게타를 완성하세요. 트리게타란? '세 방향에서 빌어와 하나로 엮인 매듭'이라는 뜻을 가진 상징으로, 세 가지가 하나로 연결됨을 의미합니다."
    },
    {
        "id": "tichu",
        "title": "티츄",
        "genre": "파티",
        "mechanism": "클라이밍",
        "minPlayers": 4,
        "maxPlayers": 4,
        "playTime": "60분",
        "difficulty": 2.34,
        "imageClass": "tichu",
        "icon": "🃏",
        "description": "티츄는 2:2 팀전 게임입니다. 한 팀이 1000점 이상 얻었을 때 더 높은 점수를 얻은 팀이 승리합니다."
    },
    {
        "id": "ttr-europe-15",
        "title": "티켓 투 라이드 : 유럽 15주년",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, 핸드 관리",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "60분",
        "difficulty": 2.0,
        "imageClass": "ttr-europe-15",
        "icon": "🚂",
        "description": "전 세계에서 가장 유명한 기차 여행 보드게임. 포호환 유럽 여행에 여러분을 초대합니다."
    },
    {
        "id": "tiki-topple",
        "title": "티키 토플",
        "genre": "패밀리",
        "mechanism": "핸드 관리, 블러핑",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 1.3,
        "imageClass": "tiki-topple",
        "icon": "🗿",
        "description": "티키상들을 이동하여 나의 목표를 이루자"
    },
    {
        "id": "faraway",
        "title": "파러웨이",
        "genre": "패밀리",
        "mechanism": "카드 드래프트",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.88,
        "imageClass": "faraway",
        "icon": "🗺️",
        "description": "안개의 바다 너머에는 신비로운 대륙 알룰라가 있습니다. 끊임없이 변하는 섬을 여행하며 알룰라의 주민을 만나 섬의 비밀을 찾고 다른 경쟁자보다 더 많은 명성을 얻으세요."
    },
    {
        "id": "foundations-of-rome",
        "title": "파운데이션 오브 롬",
        "genre": "패밀리",
        "mechanism": "영향력, 타일 놓기",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "75분",
        "difficulty": 1.96,
        "imageClass": "foundations-of-rome",
        "icon": "🏛️",
        "description": "로마에 오신 것을 환영합니다! 우리의 위대한 건국왕이신 로물루스의 요청에 따라 여러분들은 동료 건축가와 함께 이 영원한 도시에 넓은 거주지, 번화한 시장, 장엄한 기념물을 짓는 영광을 갖게 될 것입니다!"
    },
    {
        "id": "fantastic-factories",
        "title": "판타스틱 팩토리",
        "genre": "패밀리",
        "mechanism": "엔진 빌딩, 주사위",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "50분",
        "difficulty": 2.22,
        "imageClass": "fantastic-factories",
        "icon": "🏭",
        "description": "여러분만의 효율적인 공장단지를 세워서 다른 플레이어들과 경쟁 하세요. 청사진 카드를 조심스러 검토하여 여러분의 일꾼들을 훈련 시키고 최대한 많은 상품들을 생산해야 게임에서 승리할 수 있습니다.",
        "expansion": "판타스틱 팩토리 : 새로운 회사들, 기업 전쟁"
    },
    {
        "id": "for-sale-autorama",
        "title": "포세일 : 오토라마",
        "genre": "패밀리",
        "mechanism": "경매, 핸드 관리",
        "minPlayers": 3,
        "maxPlayers": 6,
        "playTime": "40분",
        "difficulty": 2.0,
        "imageClass": "for-sale-autorama",
        "icon": "🚗",
        "description": "자동차 경매를 도와줄 유능한 어드바이저를 고용하세요! 어드바이저의 능력에 따라 자동차 경매의 결과가 뒤바뀝니다. 최고 경영자가 되기 위한 당신의 선택은?"
    },
    {
        "id": "potion-explosion-10",
        "title": "포션 폭발 10주년 컬렉터스 에디션",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.75,
        "imageClass": "potion-explosion-10",
        "icon": "⚗️",
        "description": "여러분은 후러빌로룸 마법 학교의 마지막 기말고사를 앞두고 있는 마녀와 마법사들입니다. 전설의 재료를 사용해 물약을 만들고 마법 학교 최고의 우등생이 되어보세요!"
    },
    {
        "id": "pocket-farm",
        "title": "포켓팜",
        "genre": "패밀리",
        "mechanism": "퍼즐",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "20분",
        "difficulty": 1.5,
        "imageClass": "pocket-farm",
        "icon": "🧺",
        "images": "포켓팜.jpg",
        "description": "햇볕이 내리쬐고 비가 내리는 변화무쌍한 날씨를 견뎌내며 과일을 많이 담을 수 있도록 바구니를 잘 준비해보세요! 열두 달이 지난 뒤 많은 과일을 수확하면 농사의 달인이 될 수 있습니다."
    },
    {
        "id": "port-royal",
        "title": "포트로얄",
        "genre": "파티",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "30분",
        "difficulty": 1.63,
        "imageClass": "port-royal",
        "icon": "⚓",
        "description": "매일 쉴 새 없이 북적거리는 포트로얄 항구에서 플레이어는 수많은 경쟁자를 물리치고 부와 명예를 움켜쥐어야 합니다. 금화를 모아서 총독과 제독의 환심을 사고, 당신을 도와줄 여러 인물을 고용하세요. 영향력을 늘리다 보면, 명망 있는 탐험대에 사람을 파견하고 당신의 이름을 널리 알릴 수 있게 될 것입니다. 부와 명예를 얻고 이름을 알려 승점을 가장 많이 획득한 플레이어가 승리합니다."
    },
    {
        "id": "parade",
        "title": "퍼레이드",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, 핸드 관리",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.43,
        "imageClass": "parade",
        "icon": "🐱",
        "description": "이상한 나라에서 펼쳐지는 앨리스와 친구들의 축제 퍼레이드"
    },
    {
        "id": "first-rat",
        "title": "퍼스트랫",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션, 레이스",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "50분",
        "difficulty": 2.27,
        "imageClass": "first-rat",
        "icon": "🐀",
        "description": "치즈 달을 향한 고물상 쥐들의 위대한 경주."
    },
    {
        "id": "paper-safari",
        "title": "페이퍼 사파리",
        "genre": "파티",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 5,
        "playTime": "20분",
        "difficulty": 1.0,
        "imageClass": "paper-safari",
        "icon": "🦒",
        "description": "귀여운 동물 종이인형으로 당신만의 사파리를 꾸며보세요."
    },
    {
        "id": "penguin-party",
        "title": "펭귄 파티",
        "genre": "파티",
        "mechanism": "핸드 관리",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "15분",
        "difficulty": 1.12,
        "imageClass": "penguin-party",
        "icon": "🐧",
        "description": "펭귄카드를 피라미드 모양으로 내려 놓아요. 수평으로 인접한 카드 2장 이상이 나왔다면, 그 위층에 카드를 놓을 수 있습니다. 다만, 아래에 놓은 2장의 카드 2색 중 한가지 색의 카드만 놓을 수 있습니다. 더 이상 카드를 내려놓을 수 없으면, 즉시 라운드에서 빠지고 손에 남은 카드 수 만큼 벌점 토큰을 받습니다. 아무도 카드를 낼 수 없게되면 그 라운드가 끝납니다."
    },
    {
        "id": "push-fish",
        "title": "푸시 피시",
        "genre": "파티",
        "mechanism": "알까기, 셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 6,
        "playTime": "30분",
        "difficulty": 1.0,
        "imageClass": "push-fish",
        "icon": "🎣",
        "description": "손 맛이 느껴지는 본격 낚시 게임!"
    },
    {
        "id": "pueblo",
        "title": "푸에블로",
        "genre": "패밀리",
        "mechanism": "영향력, 블럭 놓기",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "60분",
        "difficulty": 2.24,
        "imageClass": "pueblo",
        "icon": "🏠",
        "description": "푸에블로는 미국 뉴멕시코 원주민들의 아름다운 진흙의 건축물을 말합니다. 여러분은 이제 푸에블로의 건축가가 되어 집을 짓습니다."
    },
    {
        "id": "project-l",
        "title": "프로젝트 L",
        "genre": "유로",
        "mechanism": "AP시스템, 타일 놓기",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "40분",
        "difficulty": 1.56,
        "imageClass": "project-l",
        "icon": "🧩",
        "description": "새로운 공간 퍼즐 등장! 퍼즐을 맞추고, 블록을 얻어 더 큰 퍼즐에 도전합니다! 최종 승리를 위한 전략을 세워가는 새로운 공간 퍼즐 게임.",
        "expansion": "프로젝트 L : 피닉스, 프로젝트 L : 고스트 블록"
    },
    {
        "id": "flamecraft",
        "title": "플레임 크래프트",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 1,
        "maxPlayers": 5,
        "playTime": "60분",
        "difficulty": 2.2,
        "imageClass": "flamecraft",
        "icon": "🐲",
        "description": "이 마을에는 창의적이고 작은 기술자인 장인 드래곤들이 함께 살고 있습니다. 여러분은 드래곤을 능숙하게 다루는 불꽃지기입니다. 드래곤과 대화하고, 적절한 상점에 배치하고, 마법을 활용해 상점 주민들을 돕고, 명성을 높이세요."
    },
    {
        "id": "film-it",
        "title": "필름을 감아!",
        "genre": "패밀리",
        "mechanism": "셋 컬렉션",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 2.0,
        "imageClass": "film-it",
        "icon": "📸",
        "description": "<필름을 감아!>는 필름의 순서를 조정하여 예쁜 사진집을 만드는 카드 게임입니다. 햇살이 비추는 동안 자신만의 방식으로 사진을 찍으세요. 피사체를 고르고, 필름을 감고, 완벽한 순간에 셔터를 누르세요. 누가 가장 아름다운 사진집을 완성할까요?"
    },
    {
        "id": "harmonies",
        "title": "하모니즈",
        "genre": "패밀리",
        "mechanism": "드래프트, 퍼즐",
        "minPlayers": 1,
        "maxPlayers": 4,
        "playTime": "30분",
        "difficulty": 2.01,
        "imageClass": "harmonies",
        "icon": "🌿",
        "description": "손바닥만 한 판 위에 여러분의 취향을 담은 작고 아름다운 생태계를 만들어 주세요. 풍경 토큰을 놓아 산, 강, 들판 등 다양한 지형을 만들고 동물들이 살아가기에 알맞은 환경이 조성되면 동물들이 저절로 찾아옵니다. 고민하여 자연을 가꾸다 보면 어느새 아름다운 풍경이 눈앞에 펼쳐져 있습니다."
    },
    {
        "id": "high-society",
        "title": "하이소사이어티",
        "genre": "패밀리",
        "mechanism": "경매",
        "minPlayers": 3,
        "maxPlayers": 5,
        "playTime": "20분",
        "difficulty": 1.49,
        "imageClass": "high-society",
        "icon": "🎩",
        "description": "자! 여기 모두가 누리고 싶어하는 삶이 경매에 나왔습니다. 남은 돈이 가장 적은 플레이어는 탈락하고, 카드 점수를 가장 많이 얻은 플레이어가 승리합니다. 최대한 많은 매물과 행운을 얻고, 불행은 최대한 피하세요."
    },
    {
        "id": "easy-come-easy-go",
        "title": "이지컴 이지고",
        "genre": "파티",
        "mechanism": "주사위",
        "minPlayers": 2,
        "maxPlayers": 4,
        "playTime": "20분",
        "difficulty": 1.02,
        "imageClass": "easy-come-easy-go",
        "icon": "🎲",
        "description": "요트 경매장에 오신것을 환영합니다! 화려하고 날렵하게 생긴 요트들이 당신의 선택을 기다리고 있습니다. 모든 요트들은 주사위 4개만 잘 굴린다면 가지고 올 수 있지요. 하지만, 기억하세요! 쉽게 가져온 요트는 쉽게 손을 떠난답니다!"
    }
];
